# Configuração base
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript

spring:
  application:
    name: cear-showcase
  
  # Web Configuration
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: PT0S # Sem cache em desenvolvimento
  
  # DevTools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/jte,src/main/resources/static
    livereload:
      enabled: true
      port: 35729

# JTE Configuration (correto para Spring Boot 3.x)
gg:
  jte:
    development-mode: true
    template-location: classpath:/jte/

# Logging para debug
logging:
  level:
    gg.jte: DEBUG
    com.cear.showcase: DEBUG
    org.springframework.web.servlet.view: DEBUG

# Actuator para debugging
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 